import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import BasketIcon from "../components/BasketIcon";
import Header from "../components/Header";
import Landing from "../components/Landing";
import Layout from "../components/Layout";
import Products from "../components/Products";
import { fetchCategories, fetchProducts } from "../utils/utils";

interface HomeProps {
  categories: Category[];
  products: Product[];
}

const Home = ({ categories, products }: HomeProps) => {
  console.log(products);
  return (
    <div>
      <Head>
        <title>Apple Redesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* navigation */}
      <Header />
      <BasketIcon />
      <main className="h-[200vh]">
        <Landing />
        <Products categories={categories} products={products} />
        {/* <section className="h-screen">jello</section> */}
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const categories: Category[] = await fetchCategories();
  const products: Product[] = await fetchProducts();
  return {
    props: {
      categories,
      products,
    },
  };
};
